#! /usr/bin/env python
# encoding: utf-8

def build(ctx):
    ctx.recurse('imagesink')
    ctx.recurse('imagesrc')
    ctx.recurse('multifilesink')
    ctx.recurse('snap')
    ctx.recurse('zcmtypes')
